// Generated by CoffeeScript 1.6.1
var Version, makeFromRaw, makeFromString, _;

_ = require("underscore");

makeFromRaw = function(params) {
  var self, v;
  self = (params ? params : this);
  v = _.values(new String(params.number));
  if (v.length < 3) {
    v = [0, 0].concat(v);
    if (v.length > 3) {
      v.shift();
    }
  }
  return v.join(self.divider);
};

makeFromString = function(params) {
  var pow, res, self, v, ver, _i, _len;
  self = (params ? params : this);
  v = params.version.split(self.divider);
  res = 0;
  pow = Math.pow(10, v.length - 1);
  for (_i = 0, _len = v.length; _i < _len; _i++) {
    ver = v[_i];
    res += parseInt(ver) * pow;
    pow /= 10;
  }
  return res;
};

Version = function(params) {
  this.created = new Date();
  this.divider = (params && params.divider ? params.divider : ".");
  this.step = (params && params.step ? params.step : 10);
  if ((params != null) && (params.number != null)) {
    this.number = params.number;
    return this.version = makeFromRaw(this);
  } else if ((params != null) && (params.version != null) && typeof params.version === 'string') {
    this.version = params.version;
    return this.number = makeFromString(this);
  } else {
    this.number = 0;
    return this.version = makeFromRaw(this);
  }
};

Version.prototype.up = function() {
  this.number++;
  this.version = makeFromRaw(this);
  return this.version;
};

module.exports = Version;
